### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ForrestPi** [Susan19900316/yolov5_tensorrt_int8#1]
使用官方 yolov5s.onnx
运行 python onnx2trt_ptq.py
出现
engine = builder.build_engine(network,config)
Segmentation fault (core dumped)
错误

**Comment by Susan19900316** [comment]
@ForrestPi 代码中 get_engine函数的
`profile= builder.create_optimization_profile()`
 `profile.set_shape(network.get_input(0).name, min=(1, 3, 384, 1280), opt=(12, 3, 384, 1280), max=(26, 3, 384, 1280))`
 `config.add_optimization_profile(profile)` 默认设定的是动态batch， shape也与官方shape不同，你看一下是否重新设置了
