### ISSUE TITLE
qat量化无法启动

### ISSUE THREAD

**Issue by Zhang-Wen-chao** [Susan19900316/yolov5_tensorrt_int8#11]
我安装了pytorch-quantization后，执行
`
python pytorch_yolov5_qat.py --weights yolov5s.pt --cfg models/yolov5s.yaml --data data/coco.yaml --img 640
`
会自动下载yolov5n.pt ， AMP check也没有通过。

我就改成了yolov5n.pt
`
python pytorch_yolov5_qat.py --weights yolov5n.pt --cfg models/yolov5n.yaml --data data/coco.yaml --img 640
`

AMP check 通过了，但是训练并没有开始，进度条不动。

**Comment by Susan19900316** [comment]
屏蔽63-64行的
`from pytorch_quantization import quant_modules`
`from pytorch_quantization import nn as quant_nn`
以及123行的`quant_modules.initialize()`
看看训练是否正常，不正常的话就是原始训练代码的问题，这块与原始的train.py的区别就是这三行代码

**Comment by Zhang-Wen-chao** [comment]
已经解决了，好像是卡太多是奇数之类的原因，指定一张卡就行了。
谢谢大佬。
