### ISSUE TITLE
qat模型导出为tensorrt后速度反而比原本的fp32模型慢

### ISSUE THREAD

**Issue by shupinghu** [Susan19900316/yolov5_tensorrt_int8#13]
你好，我将qat模型按照export_onnx_qat.py代码转成onnx，然后再利用trtexec --onnx=qat.onnx --saveEngine=qat.engine --int8获得tensorrt模型，发现推理速度反而不如原始模型使用trtexec --onnx=init.onnx --saveEngine=init.engine --fp32速度，不知道是什么原因？

**Comment by Susan19900316** [comment]
抱歉，没遇到这种情况。

**Comment by Zhang-Wen-chao** [comment]
> 你好，我将qat模型按照export_onnx_qat.py代码转成onnx，然后再利用trtexec --onnx=qat.onnx --saveEngine=qat.engine --int8获得tensorrt模型，发现推理速度反而不如原始模型使用trtexec --onnx=init.onnx --saveEngine=init.engine --fp32速度，不知道是什么原因？

请问大佬，你已经导出成功了，输入真实的图片数据是什么？我尝试了coco数据集的几张图片转的npy，都报错了，channels对不上。
