### ISSUE TITLE
W1025 19:01:36.982106 139703698719360 tensor_quantizer.py:173] Disable MaxCalibrator

### ISSUE THREAD

**Issue by Anoue** [Susan19900316/yolov5_tensorrt_int8#5]
这是怎么回事啊

**Comment by Susan19900316** [comment]
使用哪种量化方法在哪个位置报的这个错误？

**Comment by Anoue** [comment]
> 使用哪种量化方法在哪个位置报的这个错误？

int8

**Comment by Anoue** [comment]
home/ubuntu/miniconda3/envs/yolov5/lib/python3.8/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py:285: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  inputs, amax.item() / bound, 0,
/home/ubuntu/miniconda3/envs/yolov5/lib/python3.8/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py:291: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  quant_dim = list(amax.shape).index(list(amax_sequeeze.shape)[0])
/home/ubuntu/miniconda3/envs/yolov5/lib/python3.8/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py:285: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  inputs, amax.item() / bound, 0,
/home/ubuntu/miniconda3/envs/yolov5/lib/python3.8/site-packages/pytorch_quantization/nn/modules/tensor_quantizer.py:291: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  quant_dim = list(amax.shape).index(list(amax_sequeeze.shape)[0])
/home/ubuntu/tzy/yolov5s/models/yolo.py:61: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.onnx_dynamic or self.grid[i].shape[2:4] != x[i].shape[2:4]:

**Comment by Susan19900316** [comment]
@Anoue 抱歉，刚看到，我印象我转换的过程中也有这个warning，但量化后模型精度大概下降1至2个点，所以就没管此warning。
