### ISSUE TITLE
使用自定义数据集如何对int8量化后的模型进行精度损失评估

### ISSUE THREAD

**Issue by SuGuilin** [Susan19900316/yolov5_tensorrt_int8#8]
int8精度损失评估如何像val.py中对FP32和FP16的验证进行操作

**Comment by Susan19900316** [comment]
我使用的方法是 利用int8量化后的tensorrt模型对测试集或者验证集进行推理，保留推理结果，与gt进行相关指标的统计，对比fp16的相关指标，评价精度损失
