### ISSUE TITLE
QAT量化

### ISSUE THREAD

**Issue by SuGuilin** [Susan19900316/yolov5_tensorrt_int8#9]
请问QAT量化部分的代码和train.py一样，是如何进行量化的呀

**Comment by Susan19900316** [comment]
![image](https://github.com/Susan19900316/yolov5_tensorrt_int8/assets/17916585/95bf447d-2210-4025-82ff-7609c0cdad92)关注一下qat训练代码中加入的这些量，在训练中会直接用int8相关算子替换原始的算子，导出的onnx可以看到
